In [2]:
import pandas as pd
import numpy as np

In [3]:
import os

In [7]:
files = os.listdir('data/raw')

In [13]:
tables = {f: pd.read_csv('data/raw/' + f) for f in files}

In [29]:
tables['Rotacion de Pronostico.csv']

,Año/Mes,Canal distribución,Mat:Concepto Diseño,Mat:Mes Venta,Mat:Mundo,Mat:SubLinea,Mat:Tipo Articulo,Mat:Tipo de Negocio,Talla,Material,Und. Pronóstico,Und. Vendidas,% Rotación
0,1.2018,Tiendas Propias,ESCOLAR,ENERO,BEBES-FEMENINO,MODA,OVERALL LARGO,NO LINEA,12,4208147,100,2,2.00
1,1.2018,Tiendas Propias,ESCOLAR,ENERO,BEBES-FEMENINO,MODA,OVERALL LARGO,NO LINEA,18,4208147,147,10,6.80
2,1.2018,Tiendas Propias,ESCOLAR,ENERO,BEBES-FEMENINO,MODA,OVERALL LARGO,NO LINEA,24,4208147,196,13,6.63
3,1.2018,Tiendas Propias,ESCOLAR,ENERO,BEBES-FEMENINO,MODA,OVERALL LARGO,NO LINEA,2T,4208147,266,20,7.52
4,1.2018,Tiendas Propias,ESCOLAR,ENERO,BEBES-FEMENINO,MODA,OVERALL LARGO,NO LINEA,3T,4208147,317,32,10.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,1.2018,Tiendas Propias,PSYCHEDELIC NATURE,ENERO,PRIMI-MASCULINO,MODA,ZAPATOS COSIDOS,NO LINEA,15,3110246,106,9,8.49
472,1.2018,Tiendas Propias,PSYCHEDELIC NATURE,ENERO,PRIMI-MASCULINO,MODA,ZAPATOS COSIDOS,NO LINEA,16,3110246,106,8,7.55
473,1.2018,Tiendas Propias,PSYCHEDELIC NATURE,ENERO,PRIMI-MASCULINO,MODA,ZAPATOS COSIDOS,NO LINEA,17,3110246,110,14,12.73
474,1.2018,Tiendas Propias,PSYCHEDELIC NATURE,ENERO,PRIMI-MASCULINO,MODA,ZAPATOS COSIDOS,NO LINEA,18,3110246,110,18,16.36
475,1.2018,Tiendas Propias,PSYCHEDELIC NATURE,ENERO,PRIMI-MASCULINO,MODA,ZAPATOS COSIDOS,NO LINEA,19,3110246,108,14,12.96

In [45]:
tables['Base de datos proyecto Analitica.csv'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162037 entries, 0 to 162036
Data columns (total 61 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   D. Clase Fact.      162037 non-null  object
 1   # Factura           162037 non-null  int64
 2   # Pedido            162037 non-null  int64
 3   Sociedad            162037 non-null  int64
 4   C. Org. Vtas        162037 non-null  int64
 5   D. Org. Vtas        162037 non-null  object
 6   C. Canal            162037 non-null  int64
 7   D. Canal            162037 non-null  object
 8   C. Centro           162037 non-null  object
 9   D. Centro           162037 non-null  object
 10  Ciudad              162037 non-null  object
 11  C. Of. Vtas         162037 non-null  object
 12  D. Of. Vtas         162037 non-null  object
 13  F. Factura          162037 non-null  object
 14  Año Factura         162037 non-null  int64
 15  Mes Factura         162037 non-null  int64
 16  Año-Mes Factura     162037 non-null  object
 17  Día Factura         162037 non-null  int64
 18  Día Semana          162037 non-null  object
 19  H. Factura          162037 non-null  object
 20  Hora Factura        162037 non-null  int64
 21  Cod. Cliente        162037 non-null  int64
 22  Posición            162037 non-null  int64
 23  C. Material         162037 non-null  int64
 24  D. Material         162037 non-null  object
 25  valor Matriz        161741 non-null  object
 26  Talla               161741 non-null  object
 27  Color               161741 non-null  object
 28  PLU                 162037 non-null  int64
 29  Unidad              162037 non-null  object
 30  contador            71257 non-null   float64
 31  Cantidad            162037 non-null  int64
 32  Moneda              162037 non-null  object
 33  Costo Unitario      144862 non-null  float64
 34  Vlr. Bruto          162037 non-null  int64
 35  % Desc.             162037 non-null  int64
 36  Vlr. Desc.          162037 non-null  int64
 37  Vlr. Neto           162037 non-null  int64
 38  Vlr. Iva            162037 non-null  int64
 39  Vlr. Total          162037 non-null  int64
 40  Vlr. Dto Ccial VMI  144862 non-null  float64
 41  C. Usuario          162037 non-null  object
 42  C. Vendedor         162037 non-null  int64
 43  N. Vendedor         160418 non-null  object
 44  Marca               161741 non-null  object
 45  Tipo de Negocio     161741 non-null  object
 46  Destino             161741 non-null  object
 47  Año de Venta        161741 non-null  float64
 48  Mes de Venta        161741 non-null  object
 49  Edad                161741 non-null  object
 50  Género              161741 non-null  object
 51  Sublínea            161741 non-null  object
 52  Grupo de Artículo   161741 non-null  object
 53  Tipo de Artículo    160870 non-null  object
 54  Tipo de Tejido      161741 non-null  object
 55  Tipo de Referencia  161741 non-null  object
 56  País de Orígen      160067 non-null  object
 57  Saldo               161741 non-null  object
 58  Clase               161623 non-null  object
 59  Concepto Diseño     161741 non-null  object
 60  Colección           161079 non-null  float64
dtypes: float64(5), int64(21), object(35)
memory usage: 75.4+ MB

In [34]:
tables['Enero Pronostico Consolidado Final 01062020.csv']

,Temporada,Destino,Referencia,Color,Talla,Tipo Articulo,Valor Matriz,Mundo,Concepto Diseño,PVP Objetivo,Costo Objetivo,Oficina Ventas,Centro,Canal,Cantidad,Costo TT,PVP TT
0,2020/01 Enero,Todos,5110366.0,Blanco 10-0000,28,CALZADO,28 B001,Niño,Escolar,"$ 85,900","$ 26,000",Tienda Virtual,NaN,Tienda Virtual,5,"$ 130,000","$ 429,500"
1,2020/01 Enero,Todos,5110366.0,Blanco 10-0000,29,CALZADO,29 B001,Niño,Escolar,"$ 85,900","$ 26,000",Tienda Virtual,NaN,Tienda Virtual,3,"$ 78,000","$ 257,700"
2,2020/01 Enero,Todos,5110366.0,Blanco 10-0000,30,CALZADO,30 B001,Niño,Escolar,"$ 85,900","$ 26,000",Tienda Virtual,NaN,Tienda Virtual,5,"$ 130,000","$ 429,500"
3,2020/01 Enero,Todos,5110366.0,Blanco 10-0000,31,CALZADO,31 B001,Niño,Escolar,"$ 85,900","$ 26,000",Tienda Virtual,NaN,Tienda Virtual,3,"$ 78,000","$ 257,700"
4,2020/01 Enero,Todos,5110366.0,Blanco 10-0000,32,CALZADO,32 B001,Niño,Escolar,"$ 85,900","$ 26,000",Tienda Virtual,NaN,Tienda Virtual,5,"$ 130,000","$ 429,500"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72722,2020/01 Enero,Todos,5205481.0,Indigo Medio,12,PANTALON CORTO,12 I013,Niña,Sea Side,"$ 69,900","$ 18,360",Exportaciones,NaN,Internacional,52,"$ 954,720","$ 3,634,800"
72723,2020/01 Enero,Todos,5205481.0,Indigo Medio,14,PANTALON CORTO,14 I013,Niña,Sea Side,"$ 69,900","$ 18,360",Exportaciones,NaN,Internacional,51,"$ 936,360","$ 3,564,900"
72724,2020/01 Enero,Todos,5205481.0,Indigo Medio,16,PANTALON CORTO,16 I013,Niña,Sea Side,"$ 69,900","$ 18,360",Exportaciones,NaN,Internacional,45,"$ 826,200","$ 3,145,500"
72725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN